// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package tcp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type synrewriteTcpProfile struct {
	_          structs.HostLayout
	WindowSize uint16
	Ttl        uint8
	OptionsLen uint8
	Options    [40]uint8
}

// loadSynrewrite returns the embedded CollectionSpec for synrewrite.
func loadSynrewrite() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SynrewriteBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load synrewrite: %w", err)
	}

	return spec, err
}

// loadSynrewriteObjects loads synrewrite and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*synrewriteObjects
//	*synrewritePrograms
//	*synrewriteMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSynrewriteObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSynrewrite()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// synrewriteSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type synrewriteSpecs struct {
	synrewriteProgramSpecs
	synrewriteMapSpecs
	synrewriteVariableSpecs
}

// synrewriteProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type synrewriteProgramSpecs struct {
	SynRewrite *ebpf.ProgramSpec `ebpf:"syn_rewrite"`
}

// synrewriteMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type synrewriteMapSpecs struct {
	Profiles *ebpf.MapSpec `ebpf:"profiles"`
}

// synrewriteVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type synrewriteVariableSpecs struct {
}

// synrewriteObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSynrewriteObjects or ebpf.CollectionSpec.LoadAndAssign.
type synrewriteObjects struct {
	synrewritePrograms
	synrewriteMaps
	synrewriteVariables
}

func (o *synrewriteObjects) Close() error {
	return _SynrewriteClose(
		&o.synrewritePrograms,
		&o.synrewriteMaps,
	)
}

// synrewriteMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSynrewriteObjects or ebpf.CollectionSpec.LoadAndAssign.
type synrewriteMaps struct {
	Profiles *ebpf.Map `ebpf:"profiles"`
}

func (m *synrewriteMaps) Close() error {
	return _SynrewriteClose(
		m.Profiles,
	)
}

// synrewriteVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSynrewriteObjects or ebpf.CollectionSpec.LoadAndAssign.
type synrewriteVariables struct {
}

// synrewritePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSynrewriteObjects or ebpf.CollectionSpec.LoadAndAssign.
type synrewritePrograms struct {
	SynRewrite *ebpf.Program `ebpf:"syn_rewrite"`
}

func (p *synrewritePrograms) Close() error {
	return _SynrewriteClose(
		p.SynRewrite,
	)
}

func _SynrewriteClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed synrewrite_x86_bpfel.o
var _SynrewriteBytes []byte
